[package]
name = "isomdl"
version = "0.1.0"
edition = "2021"
description = "ISO mDL implementation in Rust"
readme = "README.md"
homepage = "https://github.com/spruceid/isomdl"
repository = "https://github.com/spruceid/isomdl"
license = "Apache-2.0"

[dependencies]
cose-rust = "0.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
chrono = { version =  "0.4.22", features = ["serde"] }
x509-parser = "0.14.0"
aws-nitro-enclaves-cose = "0.5.0"
openssl = "0.10.41"
ecdsa = { version = "0.14.4", features = ["serde"] }
p256 = {version = "0.11.1", features = ["serde"] }
rand_core = "0.6.3"
serde_cbor = { version = "0.11.2", features = ["tags"] }
anyhow = "1.0.62"
cddl = "0.8.7"
zeroize = { version = "1.4", features = ["zeroize_derive"] }
der = { version = "0.6.0", features = ["pem"] }
ring = "0.16.20"
rand = "0.8.5"
thiserror = "1.0.33"
