[package]
name = "isomdl"
version = "0.1.0"
edition = "2021"
description = "ISO mDL implementation in Rust"
readme = "README.md"
homepage = "https://github.com/spruceid/isomdl"
repository = "https://github.com/spruceid/isomdl"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.62"
aws-nitro-enclaves-cose = "0.5.0"
ecdsa = { version = "0.14.4", features = ["serde"] }
p256 = {version = "0.11.1", features = ["serde", "ecdh"] }
p384 = {version = "0.11.2", features = ["serde", "ecdh"] }
rand_core = {version = "0.6.3", features = ["getrandom"] }
openssl = "0.10.41"
rand = "0.8.5"
serde = { version = "1.0.143", features = ["derive"] }
serde_cbor = { version = "0.11.2", features = ["tags"] }
serde_json = "1.0.83"
sha2 = "0.10.5"
thiserror = "1.0.33"
elliptic-curve = "0.12.3"
hkdf = "0.12.3"
hex-literal = "0.3.4"
aes-gcm = "0.10.1"
hmac = "0.12.1"
aes = "0.8.1"
sec1 = "0.3.0"
uuid = { version = "1.1.2", features = ["v1", "std", "rng"] }
time = { version = "0.3.14", features = ["formatting", "parsing"] }
zeroize = { version = "1.4", features = ["zeroize_derive"] }
tracing = "0.1.37"
byteorder = "1.4.3"

[dev-dependencies]
hex = "0.4.3"
