[package]
name = "isomdl"
version = "0.1.0"
edition = "2021"
description = "ISO mDL implementation in Rust"
readme = "README.md"
homepage = "https://github.com/spruceid/isomdl"
repository = "https://github.com/spruceid/isomdl"
license = "Apache-2.0"

[dependencies]
cose-rust = "0.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
chrono = "0.4.22"
x509-parser = "0.14.0"
aws-nitro-enclaves-cose = "0.5.0"
openssl = "0.10.41"
ecdsa = "0.14.4"
p256 = "0.11.1"
rand_core = "0.6.3"
serde_cbor = "0.11.2"